__title__ = "nebsl-b2c-api"
__description__ = "The official Python client for the NEBSL B2C REST API"
__url__ = "https://github.com/giridhargk/nebslB2C"
__download_url__ = ""
__version__ = "1.0.0"
__author__ = "code161263"
__author_email__ = "code@northeastltd.com"
__license__ = "MIT"